"use client";

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronRight, Compass, Crown, Heart, LoaderCircle, LogOut, Menu, Pause, Play, Radio, RefreshCw, Search, Settings, Shield, SkipForward, ThumbsDown, UserRound, Users, WifiOff, X } from "lucide-react";
import { ApiError, authenticate, backendUrl, client, quietHour, roomCandidate, websocketUrl } from "@/lib/api";
import { formatTime, authoritativePosition } from "@/lib/timeline";
import type { Auth, ConnectionState, Presence, Snapshot, Track } from "@/lib/types";
import SceneClient from "./scene-client";
import YouTubePlayerView from "./youtube-player";

const avatars = ["round", "tall", "soft"]; const outfits = ["violet", "coral", "mint", "gold"]; const themes = ["default", "midnight", "sunset", "forest"];
const errorText = (error: unknown) => error instanceof Error ? error.message : "Something went wrong";

export default function RoomApp() {
  const [auth, setAuth] = useState<Auth | null>(null); const token = useRef("");
  const [roomId, setRoomId] = useState(""); const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [presence, setPresence] = useState<Presence[]>([]);
  const [connection, setConnection] = useState<ConnectionState>("connecting"); const [error, setError] = useState(""); const [password, setPassword] = useState(""); const [reentryRequired, setReentryRequired] = useState(false); const [reentryPending, setReentryPending] = useState(false);
  const [panel, setPanel] = useState<"queue" | "people" | "settings" | "compass" | null>("queue"); const [query, setQuery] = useState(""); const [results, setResults] = useState<Track[]>([]);
  const [recommendations, setRecommendations] = useState<Track[]>([]); const [compassEnabled, setCompassEnabled] = useState(false); const [quiet, setQuiet] = useState({ start: "22:00", end: "08:00", count: 5 });
  const [reduced, setReduced] = useState(false); const socket = useRef<WebSocket | null>(null); const reconnect = useRef<number | undefined>(undefined); const moveSent = useRef(0);
  const api = useMemo(() => token.current ? client(token.current) : null, [auth]);
  const ownId = String(auth?.user.id ?? "");
  const disabled = connection !== "online" || snapshot?.state !== "active";

  const freshAuth = useCallback(async () => {
    const initData = window.Telegram?.WebApp.initData || "";
    if (!initData) throw new Error("Open this Mini App from Telegram to authenticate.");
    const session = await authenticate(initData); token.current = session.token; setAuth(session); return session;
  }, []);

  useEffect(() => {
    const telegram = window.Telegram?.WebApp; telegram?.ready(); telegram?.expand(); telegram?.disableVerticalSwipes?.();
    setReduced(window.matchMedia("(prefers-reduced-motion: reduce)").matches || (navigator.hardwareConcurrency || 8) <= 4);
    if (!backendUrl) { setError("NEXT_PUBLIC_BACKEND_URL is not configured for this deployment."); setConnection("offline"); return; }
    freshAuth().then(session => { const candidate = roomCandidate(session.start_param); setRoomId(candidate); if (!candidate) setError("No room was supplied by Telegram. Ask for a fresh room link."); }).catch(e => { setError(errorText(e)); setConnection("offline"); });
    return () => { token.current = ""; socket.current?.close(); if (reconnect.current) clearTimeout(reconnect.current); };
  }, [freshAuth]);

  const connect = useCallback(async (id: string) => {
    if (!id || !token.current) return;
    setConnection(current => current === "online" ? "reconnecting" : "connecting"); setError("");
    try {
      const activeApi = client(token.current); const current = await activeApi.snapshot(id); setSnapshot(current);
      const { ticket } = await activeApi.ticket(id); socket.current?.close();
      const ws = new WebSocket(websocketUrl(id, ticket)); socket.current = ws;
      ws.onopen = () => setConnection("online");
      ws.onmessage = event => { const message = JSON.parse(event.data); if (message.type === "snapshot") setSnapshot((old: Snapshot | null) => !old || message.snapshot.revision >= old.revision ? message.snapshot : old); if (message.type === "presence") setPresence(message.players); };
      ws.onclose = () => { setConnection("reconnecting"); reconnect.current = window.setTimeout(() => connect(id), 1500); };
      ws.onerror = () => ws.close();
    } catch (e) {
      if (e instanceof ApiError && e.status === 401) { try { await freshAuth(); reconnect.current = window.setTimeout(() => connect(id), 100); return; } catch { setError("Telegram authentication expired. Close and relaunch the Mini App."); } }
      else if (e instanceof ApiError && e.status === 403 && e.code === "reentry_required") { setReentryRequired(true); setError(""); }
      else setError(errorText(e));
      setConnection("offline");
    }
  }, [freshAuth]);
  useEffect(() => { if (auth && roomId) connect(roomId); }, [auth, roomId, connect]);

  const join = async (event: FormEvent) => { event.preventDefault(); if (!api) return; try { setReentryRequired(false); setSnapshot(await api.join(roomId, password || undefined)); await connect(roomId); } catch (e) { if (e instanceof ApiError && e.status === 403 && e.code === "reentry_required") { setReentryRequired(true); setError(""); } else setError(errorText(e)); } };
  const requestReentry = async () => { if (!api || !roomId || reentryPending) return; try { setError(""); const result = await api.requestReentry(roomId); if (result.status === "pending") { setReentryPending(true); setReentryRequired(false); } } catch (e) { setError(errorText(e)); } };
  const act = async (action: string, payload: Record<string, unknown> = {}) => {
    if (!api || !snapshot) return;
    try { setError(""); setSnapshot(await api.action(roomId, snapshot.revision, action, payload)); }
    catch (e) {
      if (e instanceof ApiError && e.status === 409) { setError("The room changed. The latest snapshot is shown. Review and try again."); if (e.snapshot) setSnapshot(e.snapshot); else try { setSnapshot(await api.snapshot(roomId)); } catch {} }
      else if (e instanceof ApiError && e.status === 401) setError("Authentication expired. Close and relaunch the Mini App if automatic sign-in does not recover.");
      else setError(errorText(e));
    }
  };
  const search = async (event: FormEvent) => { event.preventDefault(); if (!api || !query.trim()) return; try { setResults((await api.search(query.trim())).tracks); } catch (e) { setError(errorText(e)); } };
  const sendMove = (position: Presence) => { const now = performance.now(); if (now - moveSent.current < 100 || socket.current?.readyState !== WebSocket.OPEN) return; moveSent.current = now; socket.current.send(JSON.stringify({ type: "move", x: position.x, z: position.z, rotation: position.rotation })); };
  const loadCompass = async () => { setPanel("compass"); if (api) try { setRecommendations((await api.compass()).recommendations); } catch (e) { setError(errorText(e)); } };
  if (!snapshot) return <main className="safe grid min-h-[100dvh] place-items-center p-5"><section className="panel w-full max-w-md rounded-3xl p-6 text-center"><Radio className="mx-auto text-violet-300" size={40} /><h1 className="mt-4 text-2xl font-bold">Parlay</h1><p className="mt-2 text-sm text-white/60">{connection === "connecting" ? "Authenticating and loading the room…" : error || "Room access is required."}</p>{connection === "connecting" && <LoaderCircle className="mx-auto mt-5 animate-spin" />}{roomId && connection !== "connecting" && (reentryRequired || reentryPending ? <div className="mt-5 space-y-3"><p className="text-sm text-amber-100">{reentryPending ? "Your re-entry request is pending owner approval." : "The owner must approve your re-entry."}</p><button className="w-full rounded-xl bg-amber-400/15 px-4 py-3 font-semibold text-amber-100 disabled:opacity-60" type="button" disabled={reentryPending} onClick={requestReentry}>{reentryPending ? "Request pending" : "Request re-entry"}</button></div> : <form className="mt-5 space-y-3" onSubmit={join}><input className="w-full rounded-xl border border-white/10 bg-white/5 px-4 py-3" type="password" placeholder="Room password, if required" value={password} onChange={e => setPassword(e.target.value)} /><button className="w-full rounded-xl bg-violet-500 px-4 py-3 font-semibold" type="submit">Join room</button></form>)}<p className="mt-5 text-xs text-white/40">Room links identify a room. The backend still decides admission and permissions.</p></section></main>;

  const position = authoritativePosition(snapshot.playback);
  return <main className="safe min-h-[100dvh] bg-[#090b12] p-3 lg:p-5">
    <header className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-1 pb-3"><div><div className="flex items-center gap-2"><h1 className="text-lg font-bold">Parlay Room</h1><span className={`rounded-full px-2 py-1 text-[10px] uppercase ${connection === "online" ? "bg-emerald-400/15 text-emerald-300" : "bg-amber-400/15 text-amber-200"}`}>{connection}</span></div><p className="text-xs text-white/50">{snapshot.kind === "group" ? "Telegram group voice chat" : snapshot.expires_at ? `Expires ${new Date(snapshot.expires_at * 1000).toLocaleString()}` : "Personal room"}</p></div><div className="flex gap-2"><button className="rounded-full bg-white/5 p-3" aria-label="Toggle quality" title="Toggle reduced graphics" onClick={() => setReduced(v => !v)}>{reduced ? <Check size={18} /> : <RefreshCw size={18} />}</button><button className="rounded-full bg-white/5 p-3 lg:hidden" aria-label="Open controls" onClick={() => setPanel(panel ? null : "queue")}><Menu size={18} /></button></div></header>
    {connection !== "online" && <div className="mx-auto mb-3 flex max-w-7xl items-center gap-2 rounded-xl border border-amber-300/20 bg-amber-300/10 p-3 text-sm text-amber-100"><WifiOff size={17} /> Shared controls are disabled. Reconnecting and fetching a fresh snapshot.</div>}
    {error && <div className="mx-auto mb-3 flex max-w-7xl items-start justify-between gap-2 rounded-xl border border-rose-300/20 bg-rose-300/10 p-3 text-sm text-rose-100"><span>{error}</span><button aria-label="Dismiss error" onClick={() => setError("")}><X size={17} /></button></div>}
    <div className="mx-auto grid max-w-7xl gap-3 lg:grid-cols-[minmax(0,1fr)_380px]">
      <section className="space-y-3"><div className="scene-shell relative h-[46dvh] min-h-[390px] overflow-hidden rounded-3xl border border-white/10"><SceneClient members={snapshot.members} ownId={ownId} presence={presence} theme={snapshot.settings.theme} reduced={reduced} onMove={sendMove} /><div className="pointer-events-none absolute left-3 top-3 rounded-full bg-black/45 px-3 py-2 text-xs text-white/70">Tap floor or use WASD / arrow keys to move</div></div>
      <div className="panel overflow-hidden rounded-3xl"><div className={snapshot.settings.tv_size === "large" ? "min-h-[320px]" : snapshot.settings.tv_size === "small" ? "min-h-[220px]" : "min-h-[270px]"}><YouTubePlayerView playback={snapshot.playback} /></div><div className="flex items-center gap-3 p-4"><div className="min-w-0 flex-1"><p className="truncate font-semibold">{snapshot.playback.track?.title || "Nothing playing"}</p><p className="text-xs text-white/50">{formatTime(position)} · {snapshot.playback.status}</p></div><button className="rounded-full bg-white/10 p-3" disabled={disabled || !snapshot.permissions.control} onClick={() => act(snapshot.playback.status === "playing" ? "pause" : "resume")} aria-label={snapshot.playback.status === "playing" ? "Pause room" : "Resume room"}>{snapshot.playback.status === "playing" ? <Pause /> : <Play />}</button><button className="rounded-full bg-violet-500 p-3" disabled={disabled || !snapshot.permissions.control} onClick={() => act("skip")} aria-label="Skip track"><SkipForward /></button></div><p className="px-4 pb-4 text-xs text-white/45">Local volume affects this browser only. Mute it when you also hear the Telegram voice chat to avoid double audio.</p></div></section>
      <aside className={`${panel ? "block" : "hidden"} lg:block`}><div className="panel sticky top-3 overflow-hidden rounded-3xl"><nav className="grid grid-cols-4 border-b border-white/10">{([["queue", Search], ["people", Users], ["settings", Settings], ["compass", Compass]] as const).map(([key, Icon]) => <button key={key} className={`grid place-items-center py-4 ${panel === key ? "bg-white/10 text-violet-300" : "text-white/55"}`} onClick={() => key === "compass" ? loadCompass() : setPanel(key)} aria-label={key}><Icon size={19} /></button>)}</nav><div className="max-h-[calc(100dvh-130px)] overflow-y-auto p-4">
        {panel === "queue" && <QueuePanel snapshot={snapshot} query={query} setQuery={setQuery} results={results} search={search} disabled={disabled} act={act} />}
        {panel === "people" && <PeoplePanel snapshot={snapshot} ownId={ownId} disabled={disabled} act={act} />}
        {panel === "settings" && <SettingsPanel snapshot={snapshot} disabled={disabled} act={act} />}
        {panel === "compass" && <CompassPanel enabled={compassEnabled} setEnabled={setCompassEnabled} quiet={quiet} setQuiet={setQuiet} recommendations={recommendations} disabled={disabled} save={async () => { if (!api) return; await api.compassPreferences({ enabled: compassEnabled, count: quiet.count, quiet_start: quietHour(quiet.start), quiet_end: quietHour(quiet.end), timezone: Intl.DateTimeFormat().resolvedOptions().timeZone }); }} feedback={(track, positive) => api?.compassFeedback(track.id, positive, crypto.randomUUID())} add={track => act("queue_add", { query: track.source_url || track.title })} reset={() => api?.compassReset()} remove={() => api?.compassDelete()} />}
      </div></div></aside>
    </div>
    <div className="mx-auto mt-3 flex max-w-7xl justify-end gap-2"><button className="flex items-center gap-2 rounded-xl bg-white/5 px-4 py-3 text-sm" disabled={disabled} onClick={() => act("leave")}><LogOut size={17} /> Leave</button>{snapshot.permissions.close && <button className="rounded-xl bg-rose-500/15 px-4 py-3 text-sm text-rose-200" disabled={disabled} onClick={() => act("close")}>Close room</button>}</div>
  </main>;
}

function QueuePanel({ snapshot, query, setQuery, results, search, disabled, act }: { snapshot: Snapshot; query: string; setQuery(v: string): void; results: Track[]; search(e: FormEvent): void; disabled: boolean; act(a: string, p?: Record<string, unknown>): void }) {
  return <div><h2 className="font-semibold">Find music</h2><form className="mt-3 flex gap-2" onSubmit={search}><input className="min-w-0 flex-1 rounded-xl bg-white/5 px-3 py-2" value={query} onChange={e => setQuery(e.target.value)} placeholder="Song or URL" /><button className="rounded-xl bg-violet-500 p-2" aria-label="Search"><Search /></button></form>{results.length > 0 && <div className="scrollbar-none mt-3 flex gap-2 overflow-x-auto">{results.map(track => <button key={track.id} className="shrink-0 rounded-full bg-white/10 px-3 py-2 text-xs" disabled={disabled || !snapshot.permissions.queue} onClick={() => act("queue_add", { query: track.source_url || track.title })}>+ {track.title}</button>)}</div>}<div className="mt-6 flex items-center justify-between"><h2 className="font-semibold">Up next</h2><span className="text-xs text-white/40">{snapshot.playback.queue.length}</span></div><div className="mt-2 space-y-2">{snapshot.playback.queue.map((track, i) => <div key={`${track.id}-${i}`} className="flex items-center gap-3 rounded-xl bg-white/5 p-3"><span className="text-xs text-white/35">{i + 1}</span><p className="min-w-0 flex-1 truncate text-sm">{track.title}</p></div>)}{!snapshot.playback.queue.length && <p className="py-6 text-center text-sm text-white/40">The queue is empty.</p>}</div>{snapshot.permissions.queue && <button className="mt-4 w-full rounded-xl border border-white/10 p-3 text-sm" disabled={disabled || !query.trim()} onClick={() => act("force_play", { query })}>Play search now</button>}</div>;
}
function PeoplePanel({ snapshot, ownId, disabled, act }: { snapshot: Snapshot; ownId: string; disabled: boolean; act(a: string, p?: Record<string, unknown>): void }) {
  const me = snapshot.members.find(m => String(m.user_id) === ownId);
  return <div><h2 className="font-semibold">People · {snapshot.members.length}/{snapshot.settings.capacity}</h2><div className="mt-3 space-y-2">{snapshot.members.map(member => <div key={member.user_id} className="rounded-xl bg-white/5 p-3"><div className="flex items-center gap-3">{member.photo_url ? <img src={member.photo_url} alt="" className="h-10 w-10 rounded-full object-cover" /> : <div className="grid h-10 w-10 place-items-center rounded-full bg-violet-400/20"><UserRound size={20} /></div>}<div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{member.first_name}{String(member.user_id) === ownId ? " (you)" : ""}</p><p className="flex items-center gap-1 text-xs capitalize text-white/45">{member.role === "owner" ? <Crown size={12} /> : member.role === "moderator" ? <Shield size={12} /> : null}{member.role}</p></div>{snapshot.permissions.moderate && member.role !== "owner" && String(member.user_id) !== ownId && <div className="flex gap-1"><button className="rounded-lg bg-white/5 p-2" disabled={disabled} title="Toggle moderator" onClick={() => act("moderator", { user_id: member.user_id, enabled: member.role !== "moderator" })}><Shield size={15} /></button><button className="rounded-lg bg-rose-400/10 p-2 text-rose-200" disabled={disabled} title="Remove member" onClick={() => act("kick", { user_id: member.user_id })}><X size={15} /></button></div>}</div></div>)}</div>{snapshot.pending_reentry?.length ? <div className="mt-5"><h3 className="text-sm font-semibold">Re-entry requests</h3>{snapshot.pending_reentry.map(id => <button key={id} className="mt-2 flex w-full items-center justify-between rounded-xl bg-amber-300/10 p-3 text-sm" disabled={disabled || ownId !== String(snapshot.owner_id)} onClick={() => act("approve_reentry", { user_id: id })}><span>User {id}</span><span>Approve</span></button>)}</div> : null}<div className="mt-6"><h3 className="text-sm font-semibold">Your look</h3><p className="mt-2 text-xs text-white/45">Avatar</p><div className="mt-2 flex gap-2">{avatars.map(value => <button key={value} className={`rounded-full px-3 py-2 text-xs ${me?.avatar === value ? "bg-violet-500" : "bg-white/5"}`} disabled={disabled} onClick={() => act("appearance", { avatar: value })}>{value}</button>)}</div><p className="mt-3 text-xs text-white/45">Outfit</p><div className="mt-2 flex flex-wrap gap-2">{outfits.map(value => <button key={value} className={`rounded-full px-3 py-2 text-xs ${me?.outfit === value ? "bg-violet-500" : "bg-white/5"}`} disabled={disabled} onClick={() => act("appearance", { outfit: value })}>{value}</button>)}</div></div>{!snapshot.members.some(m => String(m.user_id) === ownId) && <button className="mt-5 w-full rounded-xl bg-amber-400/15 p-3 text-amber-100" disabled={connectionUnavailable(disabled, snapshot.state)} onClick={() => act("request_reentry")}>Request re-entry</button>}</div>;
}
function connectionUnavailable(disabled: boolean, state: Snapshot["state"]) { return disabled && state !== "active"; }
function SettingsPanel({ snapshot, disabled, act }: { snapshot: Snapshot; disabled: boolean; act(a: string, p?: Record<string, unknown>): void }) {
  const [form, setForm] = useState({ capacity: snapshot.settings.capacity, password: "", owner_lock: snapshot.settings.owner_lock, queue_all: snapshot.settings.queue_all, theme: snapshot.settings.theme, tv_size: snapshot.settings.tv_size, duration: snapshot.kind === "personal" ? 7200 : 0 });
  return <form onSubmit={e => { e.preventDefault(); act("settings", form); }}><h2 className="font-semibold">Room settings</h2><label className="mt-4 block text-xs text-white/55">Capacity: {form.capacity}</label><input className="range mt-2 w-full" type="range" min="2" max="15" value={form.capacity} onChange={e => setForm({ ...form, capacity: Number(e.target.value) })} /><label className="mt-4 block text-xs text-white/55">New password (leave blank to disable password protection)</label><input className="mt-2 w-full rounded-xl bg-white/5 px-3 py-2" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} placeholder={snapshot.settings.password_required ? "Password is enabled" : "No password"} />{[["owner_lock", "Owner lock"], ["queue_all", "Everyone can add to queue"]].map(([key, label]) => <label key={key} className="mt-4 flex items-center justify-between rounded-xl bg-white/5 p-3 text-sm"><span>{label}</span><input type="checkbox" checked={Boolean(form[key as "owner_lock" | "queue_all"])} onChange={e => setForm({ ...form, [key]: e.target.checked })} /></label>)}<label className="mt-4 block text-xs text-white/55">Theme</label><select className="mt-2 w-full rounded-xl bg-white/5 p-3" value={form.theme} onChange={e => setForm({ ...form, theme: e.target.value })}>{themes.map(v => <option key={v}>{v}</option>)}</select><label className="mt-4 block text-xs text-white/55">TV size</label><select className="mt-2 w-full rounded-xl bg-white/5 p-3" value={form.tv_size} onChange={e => setForm({ ...form, tv_size: e.target.value })}><option value="small">small</option><option value="medium">medium</option><option value="large">large</option></select>{snapshot.kind === "personal" && <><label className="mt-4 block text-xs text-white/55">Lifetime: {Math.round(form.duration / 60)} minutes</label><input className="range mt-2 w-full" type="range" min="300" max="86400" step="300" value={form.duration} onChange={e => setForm({ ...form, duration: Number(e.target.value) })} /><div className="mt-3 rounded-xl border border-violet-300/15 bg-violet-300/10 p-3 text-xs text-white/65">Lifetime is measured from room creation. The saved expiry shown by the room is authoritative.</div></>}<button className="mt-5 w-full rounded-xl bg-violet-500 p-3 font-semibold" disabled={disabled || !snapshot.permissions.manage_settings}>Save settings</button>{!snapshot.permissions.manage_settings && <p className="mt-2 text-xs text-white/45">Owner Lock or group authority limits shared settings.</p>}</form>;
}
function CompassPanel({ enabled, setEnabled, quiet, setQuiet, recommendations, disabled, save, feedback, add, reset, remove }: { enabled: boolean; setEnabled(v: boolean): void; quiet: { start: string; end: string; count: number }; setQuiet(v: { start: string; end: string; count: number }): void; recommendations: Track[]; disabled: boolean; save(): Promise<void>; feedback(t: Track, p: boolean): unknown; add(t: Track): void; reset(): unknown; remove(): unknown }) {
  return <div><div className="flex items-start gap-3"><Compass className="text-violet-300" /><div><h2 className="font-semibold">Compass</h2><p className="mt-1 text-xs text-white/45">Opt in to personal recommendations and control when they appear.</p></div></div><label className="mt-5 flex items-center justify-between rounded-xl bg-white/5 p-3 text-sm"><span>Enable recommendations</span><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} /></label><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs text-white/50">Quiet from<input className="mt-1 w-full rounded-lg bg-white/5 p-2 text-white" type="time" value={quiet.start} onChange={e => setQuiet({ ...quiet, start: e.target.value })} /></label><label className="text-xs text-white/50">Quiet until<input className="mt-1 w-full rounded-lg bg-white/5 p-2 text-white" type="time" value={quiet.end} onChange={e => setQuiet({ ...quiet, end: e.target.value })} /></label></div><label className="mt-3 block text-xs text-white/50">Recommendation count: {quiet.count}<input className="range mt-2 w-full" type="range" min="1" max="10" value={quiet.count} onChange={e => setQuiet({ ...quiet, count: Number(e.target.value) })} /></label><button className="mt-4 w-full rounded-xl bg-violet-500 p-3 text-sm font-semibold" onClick={() => save()}>Save preference</button><div className="mt-5 space-y-2">{recommendations.map(track => <div key={track.id} className="rounded-xl bg-white/5 p-3"><p className="truncate text-sm font-medium">{track.title}</p><div className="mt-2 flex gap-2"><button className="rounded-lg bg-white/5 p-2" aria-label="Good recommendation" onClick={() => feedback(track, true)}><Heart size={15} /></button><button className="rounded-lg bg-white/5 p-2" aria-label="Poor recommendation" onClick={() => feedback(track, false)}><ThumbsDown size={15} /></button><button className="ml-auto flex items-center gap-1 rounded-lg bg-violet-400/15 px-2 text-xs" disabled={disabled} onClick={() => add(track)}>Queue <ChevronRight size={14} /></button></div></div>)}</div><div className="mt-6 grid grid-cols-2 gap-2"><button className="rounded-xl border border-white/10 p-3 text-xs" onClick={() => reset()}>Reset signals</button><button className="rounded-xl border border-rose-300/15 p-3 text-xs text-rose-200" onClick={() => remove()}>Delete data</button></div></div>;
}
